export const SET_MONSTER_URL = "SET_MONSTER_URL";
export const MONSTERS_IS_FETCHING = "MONSTERS_IS_FETCHING";
export const MONSTERS_FETCHING_ERROR = "MONSTERS_FETCHING_ERROR";
export const MONSTERS_FETCH_SUCCESS = "MONSTERS_FETCH_SUCCESS";
